Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jdk1.6.0_45')

library(reshape2)
library(tidyr)
library(plotly)
library(dplyr)
library(DT)
library(RJDBC)
library(rpart)
library(rpart.plot)
library(rattle)
library(data.table)

setwd("C:/Report_Automation/Accident_Decision_Tree")
drv <- JDBC("oracle.bi.jdbc.AnaJdbcDriver","bijdbc.jar")
conn <- dbConnect(drv, "jdbc:oraclebi://sprdorabiw-hq.buildings.nycnet:9703/", "username", "password")

### Since Jan 2013 f NB/A1 Enlargement permits issued and renewed
mydata<- dbGetQuery(conn, "SELECT \"- Key Segment\".\"Latitude Point\" saw_0, \"- Key Segment\".\"Longitude Point\" saw_1, \"- Permit Key Fields\".\"Borough Name\" saw_2, case WHEN \"- Permit Key Fields\".\"Job Type\" = 'NB' then ' NB' else \"- Permit Key Fields\".\"Job Type\" end saw_3, case when concat(\"- Permit Key Fields\".\"Job Type\",\"- Permit Key Fields\".\"Permit Type\")= 'NBNB' then 'New Building' when concat(\"- Permit Key Fields\".\"Job Type\",\"- Permit Key Fields\".\"Permit Type\")= 'A1AL' then ' ALT 1 Enlargement' when \"- Permit Key Fields\".\"Job Type\"='A2' then 'A2' when \"- Permit Key Fields\".\"Job Type\"='A3' then 'A3'  when \"- Permit Key Fields\".\"Job Type\"='DM' then 'DM' end saw_4, \"- Permit Key Fields\".\"Job Number\" saw_5, \"- Permit Key Fields\".\"BIN Number\" saw_6, \"- Permit Key Fields\".\"Permit Filing Status (Raw)\" saw_7, \"- Key Job Information (Job Number and Status)\".\"Job Type\" saw_8, case when \"- Key Job Information (Job Number and Status)\".\"Job Type\" = 'NB' then \"- 8 - Additional Information\".\"Total Construction Floor Area\"*148 else \"- 8 - Additional Information\".\"Estimated Job Cost\" end saw_9, \"- 8 - Additional Information\".\"Enlargement Flag (Yes/No)\" saw_10, CASE WHEN \"- Key Job Information (Job Number and Status)\".\"Job Type\" = 'A1' THEN \"- 8 - Additional Information\".\"Enlargement SQFT\" ELSE \"- 8 - Additional Information\".\"Total Construction Floor Area\" end saw_11, \"- Permit Issuance Date\".D_DATE saw_12, \"- Permit Expiration Date\".D_DATE saw_13, \"- 1- Location Information\".\"Job Location House Number\" saw_14, \"- 1- Location Information\".\"Job Location Street Name\" saw_15, \"- 1- Location Information\".\"Community Board\" saw_16, \"- Applicant Segment\".\"Applicant Business Name\" saw_17, \"- 13 - Building Characteristics\".\"Proposed Occupancy Classification Description\" saw_18, \"- 13 - Building Characteristics\".\"Proposed Stories\" saw_19, \"- 13 - Building Characteristics\".\"Proposed Dwelling Units\" saw_20 FROM \"DOB - Job Filings, v 3.0\"

WHERE (((\"- Permit Key Fields\".\"Job Type\" = 'NB') AND (\"- Permit Key Fields\".\"Permit Type\" = 'NB')) OR ((\"- Permit Key Fields\".\"Job Type\" = 'A1') AND (\"- Permit Key Fields\".\"Permit Type\" = 'AL') AND (\"- 8 - Additional Information\".\"Enlargement Flag (Yes/No)\" = 'Yes'))) AND (\"- Permit Key Fields\".\"Borough Name\" <> 'Unknown Borough Data') AND ((\"- Permit Key Fields\".\"Job Number\" LIKE '10%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '11%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '12%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '20%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '21%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '22%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '30%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '31%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '32%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '40%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '41%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '42%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '50%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '51%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '52%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '14%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '24%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '34%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '44%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '54%')) AND (\"- Permit Issuance Date\".D_DATE >= date '2013-01-01') AND (\"- Key Job Information (Job Number and Status)\".\"Withdrawal Description\" NOT IN ('Administrative Closure', 'Withdrawn')) AND (\"- Permit Key Fields\".\"BIN Number\" NOT IN ('1813361', '1813248', '1813359', '1813360')) AND (\"- Key Segment\".\"Latitude Point\" IS NOT NULL) AND (\"- Key Segment\".\"Longitude Point\" IS NOT NULL) AND (\"- Permit Key Fields\".\"Permit Filing Status (Raw)\" IN ('I', 'R')) ORDER BY saw_0, saw_1, saw_2, saw_3, saw_4, saw_5, saw_6, saw_7, saw_8, saw_9, saw_10, saw_11, saw_12, saw_13, saw_14, saw_15, saw_16, saw_17, saw_18, saw_19, saw_20")

## Change column names
names(mydata)<- c("Latitude", "Longitude", "Borough", "Job.Type", "Permit.Type", "Job.Number", "BIN", "Permit.Filing.Status", "Job.Type2", "Cost.Estimate", "Enlargement.Flag", "Square.Footage", "Permit.Issuance.Date", "Permit.Expiration.Date", "Job.Location.House.Number", "Job.Location.Street.Name", "Community.Board", "General.Contractor", "Proposed.Occupancy.Class", "Proposed.Stories", "Proposed.Dwelling.Units")

### Add in Accident Data
mydata2<- dbGetQuery(conn, "SELECT YEAR(INCIDENT_TABLE.\"Incident date (MM/DD/YYYY)\") saw_0, INCIDENT_TABLE.\"Incident date (MM/DD/YYYY)\" saw_1, INCIDENT_TABLE.Check2 saw_2, case WHEN INCIDENT_TABLE.Check2 = 'WF' then 'Worker Fell' WHEN INCIDENT_TABLE.Check2 = 'SC' then 'Scaffold/Shoring Installations' WHEN INCIDENT_TABLE.Check2 = 'CE' then 'Mechanical Construction Equipment' WHEN INCIDENT_TABLE.Check2 = 'E' then 'Excavation/Soil Work' WHEN INCIDENT_TABLE.Check2 = 'MF' then 'Material Failure (Fell)' WHEN  INCIDENT_TABLE.Check2 = 'OC' AND (INCIDENT_TABLE.\"Other Category (Construction)\" = 'Partial Demo' OR INCIDENT_TABLE.\"Other Category (Construction)\" = 'Demo' OR INCIDENT_TABLE.\"Other Category (Construction)\" = 'Demolition') then 'Demolition' WHEN  INCIDENT_TABLE.Check2 = 'OC' AND (INCIDENT_TABLE.\"Other Category (Construction)\" <> 'Partial Demo' OR INCIDENT_TABLE.\"Other Category (Construction)\" <> 'Demo' OR INCIDENT_TABLE.\"Other Category (Construction)\" <> 'Demolition' OR INCIDENT_TABLE.\"Other Category (Construction)\" Null) then 'Other Construction Related' WHEN INCIDENT_TABLE.Check2 = 'S' then 'Internal Structural Damage' WHEN INCIDENT_TABLE.Check2 = 'EE' then 'Elevator/Escalator/Amusement Ride' WHEN INCIDENT_TABLE.Check2 = 'F' then 'Facade/Envelope Failure' WHEN INCIDENT_TABLE.Check2 = 'EF' then 'Explostion/Fumes/Electrocution' WHEN INCIDENT_TABLE.Check2 = 'OE' then 'Occupancy/Other' WHEN INCIDENT_TABLE.Check2 = 'RW' then 'Retaining Wall' else 'Not Yet Determined' end saw_3, case WHEN INCIDENT_TABLE.ConstructionSiteIND = 'Y' then 'Construction Related' WHEN INCIDENT_TABLE.ConstructionSiteIND = 'N' then 'Not Construction Related' else 'Not Yet Categorized' end saw_4, CASE WHEN INCIDENT_TABLE.\"Record Type\" = 'A' THEN INCIDENT_TABLE.Fatality ELSE 0 END saw_5, CASE WHEN INCIDENT_TABLE.\"Record Type\" = 'A' THEN INCIDENT_TABLE.Injury ELSE 0 END saw_6, CASE WHEN INCIDENT_TABLE.\"Record Type\" = 'A' THEN 1 ELSE 0 END saw_7, INCIDENT_TABLE.\"Record Type\" saw_8, INCIDENT_TABLE.Boro saw_9, INCIDENT_TABLE.\"Address Number\" saw_10, INCIDENT_TABLE.Street saw_11, INCIDENT_TABLE.Block saw_12, INCIDENT_TABLE.Lot saw_13, INCIDENT_TABLE.BIN saw_14, INCIDENT_TABLE.\"Additional Address\" saw_15, INCIDENT_TABLE.\"Occupancy Class\" saw_16, INCIDENT_TABLE.\"Occupied Building\" saw_17, INCIDENT_TABLE.\"Building Type\" saw_18, INCIDENT_TABLE.\"Owner Name\" saw_19, INCIDENT_TABLE.\"Owner Address\" saw_20, INCIDENT_TABLE.\"Initial Detail of Accident\" saw_21, INCIDENT_TABLE.\"DOB Unit Notified\" saw_22 FROM \"DOB - INCIDENT_DATABASE\"
WHERE (INCIDENT_TABLE.\"Incident date (MM/DD/YYYY)\" >= timestamp '2013-01-01 00:00:00') AND (INCIDENT_TABLE.\"Record Type\" IN ('A', 'I')) AND (case WHEN INCIDENT_TABLE.ConstructionSiteIND = 'Y' then 'Construction Related' WHEN INCIDENT_TABLE.ConstructionSiteIND = 'N' then 'Not Construction Related' else 'Not Yet Categorized' end IN ('Construction Related', 'Not Yet Categorized')) AND (CASE WHEN INCIDENT_TABLE.\"Record Type\" = 'A' THEN 1 ELSE 0 END = 1) ORDER BY saw_1")

## Change column names
names(mydata2)<- c("Year", "Incident.Date", "Check2", "Incident.Type", "CR", "Fatality", "Injury", "Accident", "Record.Type", "Borough", "Address.Number", "Street", "Block", "Lot", "BIN2", "Address2", "Occupancy.Class", "Occupied.Building", "Building.Type", "Owner.Name", "Owner.Address", "Initial.Detail", "DOB.Unit.Notified")

 
### use dplyr distinct() to remove BIN duplicates.  For this exercise we only want to count BINs w/ an accident
##mydata<- mydata %>% distinct(BIN, .keep_all = TRUE)
##mydata2<- mydata2 %>% distinct(BIN2, .keep_all = TRUE)

### select BIN and Accident flag
a1<- mydata2[,c("BIN2", "Accident")]

## merge two files and add accident flag
m1 <- merge(mydata, a1, by.x = "BIN", by.y = "BIN2", all=FALSE, all.x = TRUE)

### Convert all NA to O for yes/no outcome variable)
m1$Accident[is.na(m1$Accident)] <- 0

### Remove duplicates in dataset
m1_deduped <- unique(m1)

### Active NB/A1
mydata3<- dbGetQuery(conn, "SELECT \"- Key Segment\".\"Latitude Point\" saw_0, \"- Key Segment\".\"Longitude Point\" saw_1, \"- Permit Key Fields\".\"Borough Name\" saw_2, case WHEN \"- Permit Key Fields\".\"Job Type\" = 'NB' then ' NB' else \"- Permit Key Fields\".\"Job Type\" end saw_3, case when concat(\"- Permit Key Fields\".\"Job Type\",\"- Permit Key Fields\".\"Permit Type\")= 'NBNB' then 'New Building' when concat(\"- Permit Key Fields\".\"Job Type\",\"- Permit Key Fields\".\"Permit Type\")= 'A1AL' then ' ALT 1 Enlargement' when \"- Permit Key Fields\".\"Job Type\"='A2' then 'A2' when \"- Permit Key Fields\".\"Job Type\"='A3' then 'A3'  when \"- Permit Key Fields\".\"Job Type\"='DM' then 'DM' end saw_4, \"- Permit Key Fields\".\"Job Number\" saw_5, \"- Permit Key Fields\".\"BIN Number\" saw_6, \"- Permit Key Fields\".\"Permit Filing Status (Raw)\" saw_7, \"- Key Job Information (Job Number and Status)\".\"Job Type\" saw_8, case when \"- Key Job Information (Job Number and Status)\".\"Job Type\" = 'NB' then \"- 8 - Additional Information\".\"Total Construction Floor Area\"*148 else \"- 8 - Additional Information\".\"Estimated Job Cost\" end saw_9, \"- 8 - Additional Information\".\"Enlargement Flag (Yes/No)\" saw_10, CASE WHEN \"- Key Job Information (Job Number and Status)\".\"Job Type\" = 'A1' THEN \"- 8 - Additional Information\".\"Enlargement SQFT\" ELSE \"- 8 - Additional Information\".\"Total Construction Floor Area\" end saw_11, \"- Permit Issuance Date\".D_DATE saw_12, \"- Permit Expiration Date\".D_DATE saw_13, \"- 1- Location Information\".\"Job Location House Number\" saw_14, \"- 1- Location Information\".\"Job Location Street Name\" saw_15, \"- 1- Location Information\".\"Community Board\" saw_16, \"- Applicant Segment\".\"Applicant Business Name\" saw_17, \"- 13 - Building Characteristics\".\"Proposed Occupancy Classification Description\" saw_18, \"- 13 - Building Characteristics\".\"Proposed Stories\" saw_19, \"- 13 - Building Characteristics\".\"Proposed Dwelling Units\" saw_20 FROM \"DOB - Job Filings, v 3.0\"
 
WHERE (((\"- Permit Key Fields\".\"Job Type\" = 'NB') AND (\"- Permit Key Fields\".\"Permit Type\" = 'NB')) OR ((\"- Permit Key Fields\".\"Job Type\" = 'A1') AND (\"- Permit Key Fields\".\"Permit Type\" = 'AL') AND (\"- 8 - Additional Information\".\"Enlargement Flag (Yes/No)\" = 'Yes'))) AND (\"- Permit Key Fields\".\"Borough Name\" <> 'Unknown Borough Data') AND ((\"- Permit Key Fields\".\"Job Number\" LIKE '10%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '11%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '12%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '20%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '21%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '22%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '30%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '31%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '32%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '40%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '41%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '42%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '50%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '51%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '52%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '14%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '24%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '34%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '44%' OR \"- Permit Key Fields\".\"Job Number\" LIKE '54%')) AND (\"- Permit Issuance Date\".D_DATE <=  VALUEOF(\"Today\")) AND (\"- Key Job Information (Job Number and Status)\".\"Withdrawal Description\" NOT IN ('Administrative Closure', 'Withdrawn')) AND (\"- Permit Key Fields\".\"BIN Number\" NOT IN ('1813361', '1813248', '1813359', '1813360')) AND (\"- Key Segment\".\"Latitude Point\" IS NOT NULL) AND (\"- Key Segment\".\"Longitude Point\" IS NOT NULL) AND (\"- Permit Key Fields\".\"Permit Filing Status (Raw)\" = 'I') AND (\"- Key Job Information (Job Number and Status)\".\"Current Job Status\" NOT IN ('U', 'X')) AND (\"- Permit Expiration Date\".D_DATE >=  VALUEOF(\"Today\")) AND (\"- Permit Key Fields\".\"Permit Sequence Number Max Flag\" = 'Y') ORDER BY saw_0, saw_1, saw_2, saw_3, saw_4, saw_5, saw_6, saw_7, saw_8, saw_9, saw_10, saw_11, saw_12, saw_13, saw_14, saw_15, saw_16, saw_17, saw_18, saw_19, saw_20")

 
## Change column names
names(mydata3)<- c("Latitude", "Longitude", "Borough", "Job.Type", "Permit.Type", "Job.Number", "BIN", "Permit.Filing.Status", "Job.Type2", "Cost.Estimate", "Enlargement.Flag", "Square.Footage", "Permit.Issuance.Date", "Permit.Expiration.Date", "Job.Location.House.Number", "Job.Location.Street.Name", "Community.Board", "General.Contractor", "Proposed.Occupancy.Class", "Proposed.Stories", "Proposed.Dwelling.Units")

### Create decision tree
### Must have already performed training and testing outside of script
mytree <- rpart(Accident ~ Proposed.Stories + Job.Type + Borough + Square.Footage + General.Contractor + Cost.Estimate , data = m1_deduped, method = "class", minsplit = 2, minbucket = 1)

 
## predict accident
mydata3$Accident_Pred <- predict(mytree, newdata = mydata3, type="class") #Returns the predicted class
  
## predict probability
mydata3$Accident_Prob <- predict(mytree, newdata = mydata3, type="prob") #Returns a matrix of predicted probabilities

printcp(mytree)
write.csv(mydata3, "final_active.csv")
